repos:
  - repo: local
    hooks: 
      - id: black
        name: black
        entry: black --config .black ./backend
        language: system
        types: [ python ]
        pass_filenames: false
      
      - id: flake8
        name: flake8
        entry: flake8 --config .flake ./backend
        language: system
        types: [ python ]
        pass_filenames: false

