
services:
    api: 
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        env_file:
            - .env
        ports:
            - '8000:8000'
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - database
        networks:
            - service-network
    
    database: 
        image: postgres:14.6-alpine
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - '5432:5432'
        networks:
            - service-network

    nginx:
        restart: always
        depends_on:
            - api
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - service-network

networks:
    service-network: 
        driver: bridge
    

    
