version: '3.9'

services:
    api: 
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=dbpass
            - DB_PORT=5432
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - database
        networks:
            - service-network
    
    database: 
        image: postgres:14.6-alpine
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpass
        ports:
            - '5432:5432'
        networks:
            - service-network

    nginx:
        restart: always
        depends_on:
            - api
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - service-network

networks:
    service-network: 
        driver: bridge
    

    
