name: Django CI & Postgres Test

on: ['push']

jobs:
  django_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
        SECRET_KEY: ${{ vars.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASS: ${{ vars.DB_PASS }}
        DB_PORT: 5432
    services:
      postgres_main:
        image: postgres
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 5432:5432
    steps:
      - name: print vars
        run : | 
          echo ${{ vars.DB_HOST }}
          echo ${{ vars.DB_NAME }}
          echo ${{ vars.DB_USER }}
          echo ${{ vars.SECRET_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: RUN DRF
        run: |
          python manage.py test apps/topic